### ISSUE TITLE
Missing automatic CI checks

### ISSUE THREAD

**Issue by andriyun** [OS2Forms/os2forms_forloeb#53]
In OS2Forsm drupal modules/profiles we are trying to keep coding standards and quality in good level.

Because of that there should be added ci check and test described here https://github.com/OS2Forms/docs#testing-and-ci

Implementation of standard configuration for this kind of check via Travis you can find here for example https://github.com/OS2Forms/os2forms/blob/develop/.travis.yml

**Comment by madsnorgaard** [comment]
This has been addressed. Great input and clear guide.
